#!/bin/bash
# fix_bird_config.sh - Repairs broken BIRD configurations

set -e

# Configuration
SSH_KEY_PATH="$HOME/.ssh/id_rsa"  # Adjust as needed

# Server details
declare -A SERVER_IPS=(
  ["lax"]="149.248.2.74"
  ["ewr"]="66.135.18.138"
  ["mia"]="149.28.108.180"
  ["ord"]="66.42.113.101"
)

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Function to fix BIRD configuration
fix_bird_config() {
  local server=$1
  local ip=${SERVER_IPS[$server]}
  
  echo -e "${BLUE}Fixing BIRD configuration on $server ($ip)...${NC}"
  
  ssh -i "$SSH_KEY_PATH" "root@$ip" "
    # Backup existing config if it exists
    if [ -f /etc/bird/bird.conf ]; then
      cp /etc/bird/bird.conf /etc/bird/bird.conf.bak
    fi
    
    # Create clean bird.conf
    cat > /etc/bird/bird.conf << 'EOL'
# BIRD Internet Routing Daemon Configuration
# Generated by fix_bird_config.sh

# Logging
log syslog all;
log stderr all; 

# Router ID (using WireGuard IP)
router id from \"wg0\";

# Basic protocols
protocol device {
  scan time 10;
}

protocol direct {
  ipv4;
  ipv6;
}

protocol kernel {
  ipv4 {
    export all;
  };
  learn;
}

protocol kernel {
  ipv6 {
    export all;
  };
  learn;
}

# Include configuration files
include \"/etc/bird/conf.d/ibgp_*.conf\";
EOL
    
    # Create conf.d directory if it doesn't exist
    mkdir -p /etc/bird/conf.d
    
    # Remove all previous configuration files
    rm -f /etc/ibgp.conf
    rm -f /etc/bird/conf.d/*.conf
    
    # Fix permissions
    chown -R bird:bird /etc/bird
    
    # Try to restart BIRD
    systemctl restart bird
    
    # Check if BIRD is running
    if systemctl is-active bird &> /dev/null; then
      echo 'BIRD successfully restarted!'
    else
      echo 'BIRD failed to start:'
      systemctl status bird
    fi
  "
}

# Main function
main() {
  echo -e "${BLUE}Starting BIRD configuration repair...${NC}"
  
  for server in "${!SERVER_IPS[@]}"; do
    fix_bird_config "$server"
  done
  
  echo -e "${GREEN}BIRD configuration repair completed!${NC}"
  echo -e "${YELLOW}You can now run configure_ibgp.sh to set up iBGP.${NC}"
}

# Run the main function
main