#!/bin/bash
# Script to help with DNS record creation - provides detailed manual steps

# Load environment variables
source "$(dirname "$0")/.env"

# Configuration
DOMAIN="${DOMAIN:-infinitum-nihil.com}"
ANYCAST_IPV4="192.30.120.10"
ANYCAST_IPV6="2620:71:4000::c01e:780a"
DNS_API_KEY="${DNS_API_KEY}"
DNS_API_SECRET="${DNS_API_SECRET}"

echo "============================================================"
echo "============================================================"
echo ""
echo "We've encountered issues with the DNSMadeEasy API authentication."
echo "Please follow these instructions to manually create the DNS records:"
echo ""
echo "1. Log into your DNSMadeEasy account"
echo "   URL: https://cp.dnsmadeeasy.com/"
echo ""
echo "2. Navigate to DNS > Managed DNS"
echo ""
echo "3. Select the domain: $DOMAIN"
echo ""
echo "4. Add these records:"
echo "   A. Create A record:"
echo "      - Name: lg"
echo "      - Value: $ANYCAST_IPV4"
echo "      - TTL: 300 seconds"
echo ""
echo "   B. Create AAAA record:"
echo "      - Name: lg"
echo "      - Value: $ANYCAST_IPV6"
echo "      - TTL: 300 seconds"
echo ""
echo "   C. Create A record:"
echo "      - Value: $ANYCAST_IPV4"
echo "      - TTL: 300 seconds"
echo ""
echo "   D. Create AAAA record:"
echo "      - Value: $ANYCAST_IPV6"
echo "      - TTL: 300 seconds"
echo ""
echo "5. Save all changes"
echo ""
echo "6. Verify DNS propagation with this command:"
echo "   host lg.$DOMAIN"
echo ""
echo "   This should eventually return:"
echo "   lg.$DOMAIN has address $ANYCAST_IPV4"
echo "   lg.$DOMAIN has IPv6 address $ANYCAST_IPV6"
echo ""
echo "7. After DNS propagates, your services will be available at:"
echo ""
echo "============================================================"
echo "Note: DNS propagation can take up to 24 hours, but often completes"
echo "      within a few minutes to a few hours."
echo "============================================================"

# Optional: provide additional debugging info that might help with API troubleshooting
echo ""
echo "API Debugging Information (for future reference):"
echo "------------------------------------------------"
echo "API Key: $DNS_API_KEY"
echo "Secret Key format issue? Try these conversions:"
echo "1. Without hyphens: $(echo $DNS_API_SECRET | tr -d '-')"
echo "2. Lowercase: $(echo $DNS_API_SECRET | tr '[:upper:]' '[:lower:]')"
echo "3. Lowercase without hyphens: $(echo $DNS_API_SECRET | tr -d '-' | tr '[:upper:]' '[:lower:]')"
echo ""
echo "Generate timestamps in different formats:"
echo "1. RFC1123: $(date -u "+%a, %d %b %Y %H:%M:%S GMT")"
echo "2. ISO8601: $(date -u +"%Y-%m-%dT%H:%M:%S.000Z")"
echo ""
echo "You may need to use the correct format combination for your API provider."